# Gunj Operator - golangci-lint configuration
# Version: v2.0
# Purpose: Comprehensive Go linting for CNCF compliance

# Configuration version
run:
  # Timeout for analysis
  timeout: 10m
  
  # Number of CPUs to use
  concurrency: 4
  
  # Go version
  go: '1.21'
  
  # Include test files
  tests: true
  
  # Vendor mode - skip vendor directory
  modules-download-mode: readonly
  
  # Skip directories
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - hack
  
  # Skip files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.generated\\.go$"
    - "zz_generated\\..+\\.go$"

# Output configuration
output:
  # Format: line-number, json, checkstyle, code-climate, junit-xml, github-actions
  format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true
  
  # Print linter name
  print-linter-name: true
  
  # Make issues output unique by line
  uniq-by-line: true
  
  # Sort results
  sort-results: true

# Linter settings
linters-settings:
  # errcheck - check for unchecked errors
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  # govet - Go vet checks
  govet:
    enable-all: true
    
  # golint replacement
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  
  # gofmt - format checking
  gofmt:
    simplify: true
    
  # goimports - import checking
  goimports:
    local-prefixes: github.com/gunjanjp/gunj-operator
    
  # gocyclo - cyclomatic complexity
  gocyclo:
    min-complexity: 15
    
  # gocognit - cognitive complexity
  gocognit:
    min-complexity: 20
    
  # goconst - repeated strings
  goconst:
    min-len: 3
    min-occurrences: 3
    
  # gocritic - various checks
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint
      - hugeParam
      - paramTypeCombine
      
  # gofumpt - stricter gofmt
  gofumpt:
    extra-rules: true
    
  # depguard - package imports whitelist/blacklist
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/gunjanjp/gunj-operator
          - k8s.io
          - sigs.k8s.io
          - github.com/gin-gonic/gin
          - github.com/go-logr/logr
          - github.com/prometheus/client_golang
          - github.com/stretchr/testify
          - github.com/onsi/ginkgo
          - github.com/onsi/gomega
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: "use go-logr/logr instead"
          - pkg: github.com/pkg/errors
            desc: "use fmt.Errorf with %w instead"
            
  # misspell - spell checking
  misspell:
    locale: US
    
  # lll - line length limit
  lll:
    line-length: 120
    tab-width: 4
    
  # nakedret - naked returns
  nakedret:
    max-func-lines: 30
    
  # prealloc - slice preallocation
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
    
  # unparam - unused parameters
  unparam:
    check-exported: true
    
  # whitespace
  whitespace:
    multi-if: true
    multi-func: true
    
  # wsl - whitespace linter
  wsl:
    allow-cuddle-declarations: false
    force-err-cuddling: true
    
  # gci - import order
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gunjanjp/gunj-operator)
      
  # godot - comment ending dot
  godot:
    scope: all
    capital: true
    
  # godox - TODO/FIXME/BUG comments
  godox:
    keywords:
      - TODO
      - FIXME
      - BUG
      - HACK
      - OPTIMIZE
      
  # funlen - function length
  funlen:
    lines: 80
    statements: 60
    
  # dupl - code duplication
  dupl:
    threshold: 100

# Linters to enable
linters:
  enable-all: false
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Additional linters for quality
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - ifshort
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
    
  disable:
    # Deprecated
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    
    # Too strict
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - ireturn
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck

# Issues configuration
issues:
  # Exclude specific issues
  exclude-rules:
    # Exclude test files from some linters
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gocognit
        - goconst
        - gocyclo
        - gosec
        
    # Exclude generated files
    - path: \.pb\.go
      linters:
        - all
        
    # Exclude specific directories
    - path: pkg/generated
      linters:
        - all
        
    # Exclude godox in specific files
    - path: 'cmd|internal'
      linters:
        - godox
        
    # Allow fmt.Printf in main
    - path: cmd/.+/main\.go
      linters:
        - forbidigo
        
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Show only new issues for faster feedback
  new: false
  
  # Fix found issues (if it's supported by the linter)
  fix: false

severity:
  # Default severity
  default-severity: error
  
  # Specific severities
  rules:
    - linters:
        - godox
      severity: warning
    - linters:
        - dupl
      severity: info
