# Gunj Operator - Hadolint Configuration
# Version: v2.0
# Purpose: Dockerfile linting for container best practices

# Ignored rules
ignored:
  # DL3000: Use absolute WORKDIR
  # We use relative paths in multi-stage builds
  - DL3000
  
  # DL3008: Pin versions in apt get install
  # We handle this with security scanning
  - DL3008
  
  # DL3009: Delete the apt-get lists after installing
  # We use distroless images
  - DL3009
  
  # DL3015: Avoid additional packages by specifying --no-install-recommends
  # Handled case by case
  - DL3015

# Trusted registries for FROM instructions
trustedRegistries:
  - docker.io
  - gcr.io
  - ghcr.io
  - quay.io
  - registry.k8s.io

# Label schema requirements
label-schema:
  # Mandatory labels
  org.opencontainers.image.authors: required
  org.opencontainers.image.description: required
  org.opencontainers.image.licenses: required
  org.opencontainers.image.source: required
  org.opencontainers.image.vendor: required
  org.opencontainers.image.version: required
  
  # Optional but recommended
  org.opencontainers.image.created: optional
  org.opencontainers.image.documentation: optional
  org.opencontainers.image.revision: optional
  org.opencontainers.image.title: optional
  org.opencontainers.image.url: optional

# Strict labels - must match exactly
strict-labels: true

# Failure threshold
failure-threshold: error

# Format
format: json

# Override rules  
override:
  error:
    - DL3001  # Don't use both curl and wget
    - DL3002  # Don't switch users with USER
    - DL3003  # Use WORKDIR to switch directory
    - DL3004  # Don't use sudo
    - DL3005  # Don't use apt-get upgrade
    - DL3006  # Always tag the FROM image
    - DL3007  # Use specific version tags
    - DL3010  # Use ADD for tar archives
    - DL3011  # Valid UNIX ports range
    - DL3020  # Use COPY instead of ADD for files
    - DL3021  # COPY with multiple sources to directory
    - DL3022  # COPY --from with correct syntax
    - DL3023  # Multiple CMD instructions
    - DL3024  # FROM aliases unique
    - DL3025  # Use JSON notation for CMD
    - DL3026  # Use allowed registry in FROM
    - DL3027  # Do not use apt
    - DL3029  # Do not use --platform flag
    - DL4000  # MAINTAINER is deprecated
    - DL4001  # Use wget or curl, not both
    - DL4003  # Multiple CMD, ENTRYPOINT found
    - DL4004  # Multiple ENTRYPOINT instructions
    - DL4005  # Use SHELL to change shell
    - DL4006  # Add pipefail
    - SC1091  # Not following sourced files
    
  warning:
    - DL3012  # Multiple consecutive RUN
    - DL3013  # Pin versions in pip
    - DL3016  # Pin versions in npm
    - DL3018  # Pin versions in apk add
    - DL3019  # Use --no-cache in apk
    - DL3028  # Pin versions in gem install
    - DL3030  # Use yum clean after yum install
    - DL3032  # Pin versions in yum install
    - DL3033  # Pin versions in zypper install
    - DL3034  # Use zypper clean after zypper install
    - DL3035  # Pin versions in dnf install
    - DL3036  # Use dnf clean after dnf install
    - DL3037  # Pin versions in microdnf install
    - DL3038  # Use microdnf clean after microdnf install
    - DL3041  # Pin versions in dnf install
    - DL3042  # Cache pip packages
    - DL3045  # COPY to relative WORKDIR
    - DL3047  # Use wget --no-verbose
    - DL3048  # Invalid label key
    - DL3049  # Label with reserved namespace
    - DL3050  # Superfluous label keys
    - DL3051  # Label is empty
    - DL3052  # Label is not URL
    - DL3053  # Label is not RFC3339 date
    - DL3054  # Label is not SPDX license
    - DL3055  # Label is not git hash
    - DL3056  # Label does not conform to semantic versioning
    - DL3057  # HEALTHCHECK instruction missing
    - DL3058  # Multiple HEALTHCHECK instructions
    - DL3059  # Multiple consecutive RUN
    - DL3060  # Use yarn cache clean after yarn install
    - DL4005  # Use SHELL to change shell
