# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: gunj-operator
    app.kubernetes.io/instance: gunj-operator
    app.kubernetes.io/component: certificate
  name: gunj-operator-selfsigned-issuer
  namespace: gunj-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: gunj-operator
    app.kubernetes.io/instance: gunj-operator
    app.kubernetes.io/component: certificate
  name: gunj-operator-serving-cert
  namespace: gunj-system
spec:
  dnsNames:
  - gunj-operator-webhook-service.gunj-system.svc
  - gunj-operator-webhook-service.gunj-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: gunj-operator-selfsigned-issuer
  secretName: webhook-server-cert
