---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gunj-operator
    app.kubernetes.io/instance: gunj-operator
    app.kubernetes.io/component: webhook
  name: gunj-operator-webhook-service
  namespace: gunj-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: gunj-operator
    app.kubernetes.io/instance: gunj-operator
    app.kubernetes.io/component: operator
