# Role for managing ObservabilityPlatform resources and their status
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gunj-operator-manager-role
  labels:
    app.kubernetes.io/name: gunj-operator
    app.kubernetes.io/managed-by: kustomize
rules:
# ObservabilityPlatform resource permissions
- apiGroups:
  - observability.io
  resources:
  - observabilityplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# ObservabilityPlatform status subresource permissions
# This allows the operator to update status independently
- apiGroups:
  - observability.io
  resources:
  - observabilityplatforms/status
  verbs:
  - get
  - patch
  - update

# ObservabilityPlatform finalizers permissions
- apiGroups:
  - observability.io
  resources:
  - observabilityplatforms/finalizers
  verbs:
  - update

# Permissions for managing Prometheus resources
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - prometheusrules
  - servicemonitors
  - podmonitors
  - alertmanagers
  - alertmanagerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing core Kubernetes resources
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing apps resources
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing networking resources
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing RBAC resources
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing policy resources
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for managing autoscaling resources
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Permissions for leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - watch

# Permissions for watching nodes (for scheduling decisions)
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch

# Permissions for creating events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
