# This patch enables conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: observabilityplatforms.observability.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: gunj-webhook-service
          namespace: gunj-system
          path: /convert
        caBundle: Cg==
      conversionReviewVersions:
      - v1
      - v1beta1
