# Kind Cluster Configuration for Development
# Single node cluster with port mappings for ingress
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gunj-operator-dev
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # HTTP
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # HTTPS  
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # API Server (for external access)
  - containerPort: 8443
    hostPort: 8443
    protocol: TCP
  # Prometheus
  - containerPort: 30090
    hostPort: 9090
    protocol: TCP
  # Grafana
  - containerPort: 30300
    hostPort: 3000
    protocol: TCP
  # Local Registry
  - containerPort: 30500
    hostPort: 5000
    protocol: TCP
# Mount local directories for development
  extraMounts:
  - hostPath: ./config
    containerPath: /gunj-operator/config
    readOnly: true
  - hostPath: ./bin
    containerPath: /gunj-operator/bin
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
# Networking configuration
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false
  kubeProxyMode: "ipvs"
