# Example: Minimal ObservabilityPlatform for development
apiVersion: observability.io/v1beta1
kind: ObservabilityPlatform
metadata:
  name: dev-platform
  namespace: observability
spec:
  # Minimal component configuration
  components:
    prometheus:
      enabled: true
      version: v2.48.0
      storage:
        size: 10Gi
    
    grafana:
      enabled: true
      version: "10.2.0"
      ingress:
        enabled: true
        host: grafana.localhost
        
    loki:
      enabled: true
      version: v2.9.0
      storage:
        size: 20Gi
