# This kustomization.yaml adds webhook conversion patches to the CRDs
resources:
- bases/observability.io_observabilityplatforms.yaml

patchesStrategicMerge:
- patches/webhook_in_observabilityplatform.yaml

# JSON patches for more complex modifications
patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: observabilityplatforms.observability.io
  path: patches/conversion_webhook_patch.yaml

# The following config is for teaching kustomize how to update name ref and var substitution
configurations:
- kustomizeconfig.yaml
